name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: true

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: ~> v2
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  homebrew:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GH_PAT }}
          tap: arturtamborski/tap
          formula: kredens
          tag: ${{ github.ref_name }}
