name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: ~> v2
          distribution: goreleaser
          args: release --clean

      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          tap: arturtamborski/tap
          formula: kredens
          tag: ${{ github.ref_name }}
